import Collapser from "@/components/collapser";
import "./globals.scss";
import { Manrope } from "next/font/google";
import Sidebar from "./sidebar";
import ButtonToggleSidebar from "./toggleSidebar";

const font = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Collapser width={330}>
          <Sidebar
            leading={
              <ButtonToggleSidebar
                hideOnHidden
                color="dark"
                className="ml-auto"
              />
            }
          />
        </Collapser>
        {children}
      </body>
    </html>
  );
}
