import "./globals.scss";
import { Manrope } from "next/font/google";
import { AppSidebar } from "../fragments";

const font = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AppSidebar />
        {children}
      </body>
    </html>
  );
}
